#!/usr/bin/env bash
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_AVAILABLE_PATH/config/functions"

s2-portal-config() {
  declare BUILDER_TYPE="$1" APP="$2"

  # set additional config values, will end up as env vars in the container

  # dokku app name
  config_set --no-restart "$APP" DOKKU_APP_NAME="$APP"
}

s2-portal-config "$@"
